config/routes.rb
Rails.application.routes.draw do

  namespace :api do

    resources :categories, except: [:new, :edit]
  end

  #send users to the welcome page upon arrival
  root 'pages#index'

  #basic static pages, welcome, about, and contact
  get 'pages/index' => 'pages#index', as: :welcome

  get 'pages/about' => 'pages#about', as: :about

  get 'pages/dashboard' => 'pages#dashboard', as: :dashboard

  get 'pages/hashboard' => 'pages#hashboard', as: :hashboard

  #create a new session for twitter oauth
  get '/auth/:provider/callback' => 'sessions#create', as: :twitter

  #delete session for twitter oauth
  delete '/logout' => 'sessions#destroy'

  get 'labels/index' => 'labels#index', as: :labels

  get 'labels/show/:id' => 'labels#show', as: :label

  get 'labels/new' => 'labels#new', as: :new_label

  post 'labels/create' => 'labels#create'

  post 'api/categories/rank_tags' => 'api/categories#rank_tags'

  #get all the current tweet in our db
  get 'tweets/index' => 'tweets#index', as: :tweets

  #compose a new tweet
  get 'tweets/new' => 'tweets#new', as: :new_tweet

  #create the tweet on your twitter account
  post 'tweets/create' => 'tweets#create'

  #hit the twitter REST API and get some tweets for the db
  post 'tweets/get_latest' => 'tweets#get_latest'

  post 'tweets/get_latest' => 'tweets#get_latest'
end

app/views/shared/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l4 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <a class="waves-effect waves-light btn" href="https://twitter.com/hash_robot" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @hash_robot</a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
          <!--<li> <%= link_to 'Analyze Tweets', new_label_path,'class' => 'grey-text text-lighten-3'%> </li>-->
          <a class="waves-effect waves-light btn" href="mailto:hashrobot.dtla@gmail.com">Email Us!</a>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2015 HashRobot
    </div>
  </div>
</footer>

app/views/shared/_nav.html.erb
<nav>
  <div class="nav-wrapper">
    <div class="container">
      <a href="http://www.hashrobot.com" class="brand-logo"><%=	image_tag 'hashrobot_xs.png' %></a>
      <div id="nav-mobile" class="right hide-on-med-and-down">
        <% if current_user %>
          <%= link_to 'Log Out', logout_path, method: :delete, 'class' => 'nav-logout-link' %>
          <%= image_tag current_user.image_url, alt: current_user.name, 'class' => 'user-image' %>
        <% else %>
          <%= button_tag(:class => 'waves-effect waves-light btn welcome-btn') do %>
            <a href="/auth/twitter">Login with Twitter</a>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</nav>
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
</div>