config/routes.rb
Rails.application.routes.draw do

  namespace :api do

    resources :categories, except: [:new, :edit]
  end

  #send users to the welcome page upon arrival
  root 'pages#index'

  #basic static pages, welcome, about, and contact
  get 'pages/index' => 'pages#index', as: :welcome

  get 'pages/about' => 'pages#about', as: :about

  get 'pages/dashboard' => 'pages#dashboard', as: :dashboard

  get 'pages/hashboard' => 'pages#hashboard', as: :hashboard

  #create a new session for twitter oauth
  get '/auth/:provider/callback' => 'sessions#create', as: :twitter

  #delete session for twitter oauth
  delete '/logout' => 'sessions#destroy'

  get 'labels/index' => 'labels#index', as: :labels

  get 'labels/show/:id' => 'labels#show', as: :label

  get 'labels/new' => 'labels#new', as: :new_label

  post 'labels/create' => 'labels#create'

  post 'api/categories/rank_tags' => 'api/categories#rank_tags'

  #get all the current tweet in our db
  get 'tweets/index' => 'tweets#index', as: :tweets

  #compose a new tweet
  get 'tweets/new' => 'tweets#new', as: :new_tweet

  #create the tweet on your twitter account
  post 'tweets/create' => 'tweets#create'

  #hit the twitter REST API and get some tweets for the db
  post 'tweets/get_latest' => 'tweets#get_latest'

  post 'tweets/get_latest' => 'tweets#get_latest'
end

app/views/pages/about.html.erb
<div class="container">
  <h2>About #Robot</h2>

  <h4>Purpose</h4>
  <p>
    #Robot will give the user the best hast tag choices based on a chosen category.
    Users can then tweet right from the application with the suggested hash tags.
  </p>

  <h4>Design</h4>
  <p>
    #Robot is designed to ingest large numbers of tweets from Twitter's API.
    It then passes them to the Monkey Learn API to get the relevant category for a particular tweet.
    It then finds the most used hash tags for a particular category and returns those to a user upon request.
  </p>

  <h4>Creators</h4>
  <p>
    #Robot was created by Ryan Smith, Jeff Demers, and Chris Wu
    while taking General Assembly's 12-week Web Development Immersive program.
  </p>
</div>

app/views/pages/dashboard.html.erb
<% if current_user && current_user.id == 1 %>
  <div class="container">

    <h3>Dashboard</h3>

  <div class = row>
    <div class="col s12 m4 center">
      <%= form_tag('/tweets/get_latest')do %>
        <%= text_field_tag :tweet_location, nil, :placeholder => "e.g. 34.101509,-118.32691" %>
        <%= button_tag(:class => 'btn') do %>
            <i class="fa fa-twitter"></i> &nbsp; Get Tweets
        <% end %>
      <% end %>
    </div>

    <div class="col s12 m4 center">
      <%= form_tag('/labels/create')do %>
        <%= button_tag(:class => 'btn') do %>
            <i class="fa fa-twitter"></i> &nbsp; Categorize Tweets
        <% end %>
      <% end %>
    </div>

    <div class="col s12 m4 center">
      <%= form_tag('/api/categories/rank_tags')do %>
        <%= button_tag(:class => 'btn') do %>
            <i class="fa fa-twitter"></i> &nbsp; Rank Tags
        <% end %>
      <% end %>
    </div>
  </div>

    <h5>All Tweets</h5>

    <div class="col s8, scroll">

      <% @tweets.each do |tweet| %>

          <%= tweet.id%>
          <%= tweet.content%>
          <%= tweet.created%>
          <br>

      <% end %>

    </div>
  </div>
<% end %>

app/views/pages/hashboard.html.erb
<div class="container">
  <h3 class="center">Welcome to the #Board</h3>
  <div class="result"></div>

  <!-- Dropdown Trigger -->
  <a class='dropdown-button btn' href='' data-activates='dropdown1' id="category-dropdown">Pick a Category</a>

  <!-- Dropdown Structure -->
  <div class="category-picker">
    <ul id='dropdown1' class='dropdown-content'></ul>
  </div>

  <div class="tag-results"></div>

  <% if current_user %>
    <div class="tweet-box">
      <%= form_tag('/tweets/create')do %>
        <%= text_field_tag :tweet_body, nil, :placeholder => "Enter tweet here" %>
        <%= button_tag(:class => 'btn') do %>
         <i class="fa fa-twitter tooltipped" data-position="top" data-delay="5" data-tooltip="Send a tweet!"></i> &nbsp; Tweet!
        <% end %>
      <% end %>
    </div>
    <br>
  <% end %>


</div>

app/views/pages/index.html.erb
<div class="section info jumbotron">
  <div class="row container">
    <div class = row>
      <div class="col s12 m12 center">
        <h1 class="jumbotron-header">#Robot</h1>
        <h5>Great content deserves to be #noticed.</h5>
        <% if current_user %>
          <%= link_to 'Log Out', logout_path, method: :delete, 'class' => 'waves-effect waves-light btn-large welcome-btn' %>
          <%= link_to '#board', hashboard_path, 'class' => 'waves-effect waves-light btn-large welcome-btn' %>
        <% else %>
          <%= button_tag(:class => 'waves-effect waves-light btn-large welcome-btn') do %>
            <a href="/auth/twitter">Login with Twitter</a>
          <% end %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="parallax-container parallax-container-1">
  <div class="parallax"><%=	image_tag 'colorful-robots-sm.jpg' %></div>
</div>

<div class="section info">
  <h4 class="main_title center">Make a big impact with your social media content.</h4>
     <div class ="row center">
       <div class="col s12 m4 l4">
         <i class="large material-icons">trending_up</i>
         <h5 class="main_title">Goal</h5>
             <p class="about">#Robot is your personal marketing consultant.
               <br><br>#Robot will give the most visible and used hashtags in each category. Adding these hashtags to your tweets will give social media users an edge in getting views and gaining followers.
               <br><br>#Robot makes it easy for you to tweet right from our hash dash!
             </p>
       </div>
       <div class="col s12 m4 l4">
         <i class="large material-icons">track_changes</i>
         <h5 class="main_title">Design</h5>
             <p class="about"> #Robot is designed to process large numbers of current and popular tweets from Twitter's API.
                 #Robot then passes them to the MonkeyLearn API to gain data and relevant categories for a each tweet.
                 #Robot reivews the results applies its proprietary algorithm then finds the most valuable hash tags for a each category at a given moment.
               <br> <br> These hashtags can then be used to raise your social media profile!
             </p>
       </div>
       <div class="col s12 m4 l4">
        <i class="large material-icons">web</i>
          <h5 class="main_title">Architecture</h5>
              <ul class="about">
                <li>Language processing via <a href="http://monkeylearn.com/">MonkeyLearn</a></li>
                <li>Data from <a href="https://twitter.com/">Twitter</a></li>
                <li>Hosted on <a href="https://www.heroku.com/">Heroku</a></li>
                <li>Built on <a href="http://rubyonrails.org/">Rails</a> and a bit of <a href="https://jquery.com/">jQuery</a></li>
                <li><a href="http://materializecss.com/">Materialize</a> for CSS</li>
                <li>Icons from <a href="https://fortawesome.github.io/Font-Awesome/icons/">Font Awesome</a></li>
                <li>Fonts from <a href="https://www.google.com/fonts">Google fonts</a></li>
                <li>Check us out on <a href="https://github.com/rysmith/hashrobot">GitHub</a></li>
              </ul>
        </div>
      </div>
  </div>
</div>

<div class="parallax-container">
  <div class="parallax"><%=	image_tag 'creators_bg.png' %></div>
</div>

<div class="parallax-container pictures">
  <div class="section">
    <div class="row container">
      <div class="row">
        <div class="col s12 center about">
          <h2 class="main_title">Creators</h2>
          <h5>
            Conceived and created during General Assembly's 12-week <a href="https://generalassemb.ly/education/web-development-immersive/los-angeles">WDI</a> program.
          </h5>
        </div>
      </div>
      <div class="row">
        <div class="col s12 m4 center">
          <div class="creators">
            <a href="https://www.linkedin.com/in/jeffreydemers"><%= image_tag "jeff_head.png" %></a>
            <h4><a href="https://www.linkedin.com/in/jeffreydemers">Jeff Demers</a></h4>
          </div>
        </div>
        <div class="col s12 m4 center">
          <div class="creators">
            <a href="http://ryansmith.io/"><%= image_tag "ryan_head.png" %></a>
            <h4><a href="http://ryansmith.io/">Ryan Smith</a></h4>
          </div>
        </div>
        <div class="col s12 m4 center">
          <div class="creators">
            <a href="https://wakarana1.github.io"><%= image_tag "chris_head.png" %></a>
            <a href="https://wakarana1.github.io"><h4>Chris Wu</a></h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="parallax-container  parallax-container-1">
  <div class="parallax"><%=	image_tag 'colorful-robots-sm.jpg' %></div>
</div>